# prep storage for frontend-cms public uploads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: otk-cms-pv-volume
  namespace: otk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/otk/cms-public-uploads"
---
# CMS Pub storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otk-cms-pv-claim
  namespace: otk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi