#frontend-cms.yaml
apiVersion: v1
kind: Secret
metadata:
  name: frontend-cms-secret
  namespace: otk
type: Opaque
stringData:
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_FROM: ""
  SMTP_REPLYTO: ""

---
#termservice.yaml, discussionService.yaml
apiVersion: v1
kind: Secret
metadata:
  name: termservice-secret
  namespace: otk
type: Opaque
stringData:
  Auth__BasicAuth__Password: ""
  Auth__BasicAuth__Username: ""
  Auth__JwtBearer__Secret: ""
  ConnectionStrings__termDB: ""
  ConnectionStrings__discussionDB: ""

---
#keycloak.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: otk
type: Opaque
stringData:
  KEYCLOAK_USER: ""
  KEYCLOAK_PASSWORD: ""
  DB_PASSWORD: ""
  DB_USER: ""

---
#kibana.yaml
apiVersion: v1
kind: ConfigMap
metadata:
 name: kibana-config
 namespace: otk
data:
 ELASTICSEARCH_HOSTS: "http://elasticserch:2022/"
---